version: "3.8"
services:
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: que_go_test
    volumes:
      # Run init script
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

