# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: debian:jessie

    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: que_go_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install postgres
        run: apt-get update && apt-get install postgresql
        
      - name: Check out repository code
        uses: actions/checkout@v2


      - name: Run Schema
        run: psql "postgres://postgres:postgres@localhost/que_go_test" -f schema.sql


      - name: Test
        run: go test ./...
